import type { Metadata } from "next";
import { Quicksand, Geist_Mono, Marck_Script } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const marckscript = Marck_Script({
  variable: "--font-marckscript",
  subsets: ["latin"],
  weight: "400",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${marckscript.variable} antialiased w-full font-sans`}
        style={{ fontFamily: "var(--font-quicksand)" }}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
