import type { Metadata } from "next";
import { Quicksand, Marck_Script } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import SmoothScroll from "@/components/common/SmoothScroll";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const marckscript = Marck_Script({
  variable: "--font-marckscript",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Little Alpha Bikaner | Discover Bright Beginnings",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-IN">
      <body
        className={`${quicksand.variable} ${marckscript.variable} antialiased w-full`}
      >
        <SmoothScroll>
          <Navbar />
          <NextTopLoader />
        {children}
          <Toaster />
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
